# Generated by Django 5.1.6 on 2025-03-31 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Amenity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название удобства"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("main", "Основные"),
                            ("kitchen", "Кухня"),
                            ("bedroom", "Спальня"),
                            ("bathroom", "Ванная комната"),
                            ("other", "Другое"),
                        ],
                        max_length=20,
                        verbose_name="Категория",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Apartment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Цена"
                    ),
                ),
                ("city", models.CharField(max_length=100, verbose_name="Город")),
                ("address", models.CharField(max_length=255, verbose_name="Адрес")),
                ("latitude", models.FloatField(verbose_name="Широта")),
                ("longitude", models.FloatField(verbose_name="Долгота")),
                ("rooms", models.IntegerField(verbose_name="Количество комнат")),
                ("square_meters", models.FloatField(verbose_name="Квадратные метры")),
                (
                    "max_people",
                    models.IntegerField(verbose_name="Максимальное количество человек"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("RENT", "Аренда"), ("SALE", "Продажа")],
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата добавления"
                    ),
                ),
                (
                    "images",
                    models.JSONField(blank=True, default=list, verbose_name="Фото"),
                ),
                (
                    "amenities",
                    models.ManyToManyField(
                        blank=True,
                        related_name="apartments",
                        to="listings.amenity",
                        verbose_name="Удобства",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apartments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ViewHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "viewed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата просмотра"
                    ),
                ),
                (
                    "apartment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="viewed_by",
                        to="listings.apartment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="view_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "apartment")},
            },
        ),
    ]
