# Generated by Django 5.1.6 on 2025-03-31 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0002_amenity_apartment_viewhistory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apartment",
            name="images",
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="apartment_photos/")),
                (
                    "apartment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="listings.apartment",
                    ),
                ),
            ],
        ),
    ]
