# Generated by Django 5.1.6 on 2025-04-01 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0003_remove_apartment_images_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apartment",
            name="latitude",
            field=models.FloatField(blank=True, null=True, verbose_name="Широта"),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="longitude",
            field=models.FloatField(blank=True, null=True, verbose_name="Долгота"),
        ),
    ]
