# Generated by Django 5.1.6 on 2025-04-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0004_alter_apartment_latitude_alter_apartment_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="apartment",
            name="total_views",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Общее количество просмотров"
            ),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Цена (сутки)"
            ),
        ),
    ]
