# Generated by Django 5.1.6 on 2025-04-06 13:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0005_apartment_total_views_alter_apartment_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apartment",
            name="max_people",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Максимальное количество человек",
            ),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Цена (сутки)",
            ),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="rooms",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Количество комнат",
            ),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="square_meters",
            field=models.FloatField(
                validators=[django.core.validators.MinValueValidator(10)],
                verbose_name="Квадратные метры",
            ),
        ),
    ]
