# Generated by Django 5.1.6 on 2025-04-06 14:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0006_alter_apartment_max_people_alter_apartment_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="apartment",
            name="currency",
            field=models.CharField(
                choices=[("RUB", "Рубль"), ("USD", "Доллар США"), ("EUR", "Евро")],
                default="RUB",
                max_length=3,
                verbose_name="Валюта",
            ),
        ),
        migrations.AddField(
            model_name="apartment",
            name="rental_period",
            field=models.CharField(
                blank=True,
                choices=[("DAILY", "Сутки"), ("MONTHLY", "Месяц")],
                help_text="Выберите период сдачи, если объявление — аренда (сутки или месяц)",
                max_length=10,
                null=True,
                verbose_name="Период сдачи",
            ),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="max_people",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Максимальное количество человек",
            ),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Цена",
            ),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="rooms",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Количество комнат",
            ),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="square_meters",
            field=models.FloatField(
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Квадратные метры",
            ),
        ),
    ]
