name: myenv_rental
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - postgresql
  - scikit-learn
  - pip:
      - django==5.1.6
      - pillow==11.1.0
      - psycopg2-binary==2.9.10
      - djangorestframework==3.15.2
      - requests==2.32.3
      - python-dotenv
