services:
  - type: web
    name: rental-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn rental.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: rental.settings
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: DATABASE_URL
        fromDatabase:
          name: rental_db
          property: connectionString

databases:
  - name: rental_db
